package winbackoffers

import (
	"context"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/peterbourgon/ff/v3/ffcli"

	"github.com/rudrankriyam/App-Store-Connect-CLI/internal/asc"
	"github.com/rudrankriyam/App-Store-Connect-CLI/internal/cli/shared"
)

const (
	winBackOffersMaxLimit       = 200
	winBackOffersPricesMaxLimit = 50
)

var winBackOfferDurationValues = []string{
	string(asc.SubscriptionOfferDurationThreeDays),
	string(asc.SubscriptionOfferDurationOneWeek),
	string(asc.SubscriptionOfferDurationTwoWeeks),
	string(asc.SubscriptionOfferDurationOneMonth),
	string(asc.SubscriptionOfferDurationTwoMonths),
	string(asc.SubscriptionOfferDurationThreeMonths),
	string(asc.SubscriptionOfferDurationSixMonths),
	string(asc.SubscriptionOfferDurationOneYear),
}

var winBackOfferDurationMap = map[string]asc.SubscriptionOfferDuration{
	string(asc.SubscriptionOfferDurationThreeDays):   asc.SubscriptionOfferDurationThreeDays,
	string(asc.SubscriptionOfferDurationOneWeek):     asc.SubscriptionOfferDurationOneWeek,
	string(asc.SubscriptionOfferDurationTwoWeeks):    asc.SubscriptionOfferDurationTwoWeeks,
	string(asc.SubscriptionOfferDurationOneMonth):    asc.SubscriptionOfferDurationOneMonth,
	string(asc.SubscriptionOfferDurationTwoMonths):   asc.SubscriptionOfferDurationTwoMonths,
	string(asc.SubscriptionOfferDurationThreeMonths): asc.SubscriptionOfferDurationThreeMonths,
	string(asc.SubscriptionOfferDurationSixMonths):   asc.SubscriptionOfferDurationSixMonths,
	string(asc.SubscriptionOfferDurationOneYear):     asc.SubscriptionOfferDurationOneYear,
}

var winBackOfferModeValues = []string{
	string(asc.SubscriptionOfferModePayAsYouGo),
	string(asc.SubscriptionOfferModePayUpFront),
	string(asc.SubscriptionOfferModeFreeTrial),
}

var winBackOfferModeMap = map[string]asc.SubscriptionOfferMode{
	string(asc.SubscriptionOfferModePayAsYouGo): asc.SubscriptionOfferModePayAsYouGo,
	string(asc.SubscriptionOfferModePayUpFront): asc.SubscriptionOfferModePayUpFront,
	string(asc.SubscriptionOfferModeFreeTrial):  asc.SubscriptionOfferModeFreeTrial,
}

var winBackOfferPriorityValues = []string{
	string(asc.WinBackOfferPriorityHigh),
	string(asc.WinBackOfferPriorityNormal),
}

var winBackOfferPriorityMap = map[string]asc.WinBackOfferPriority{
	string(asc.WinBackOfferPriorityHigh):   asc.WinBackOfferPriorityHigh,
	string(asc.WinBackOfferPriorityNormal): asc.WinBackOfferPriorityNormal,
}

var winBackOfferPromotionIntentValues = []string{
	string(asc.WinBackOfferPromotionNotPromoted),
	string(asc.WinBackOfferPromotionUseAutoGeneratedAssets),
}

var winBackOfferPromotionIntentMap = map[string]asc.WinBackOfferPromotionIntent{
	string(asc.WinBackOfferPromotionNotPromoted):            asc.WinBackOfferPromotionNotPromoted,
	string(asc.WinBackOfferPromotionUseAutoGeneratedAssets): asc.WinBackOfferPromotionUseAutoGeneratedAssets,
}

// WinBackOffersCommand returns the win-back offers command group.
func WinBackOffersCommand() *ffcli.Command {
	fs := flag.NewFlagSet("win-back-offers", flag.ExitOnError)

	return &ffcli.Command{
		Name:       "win-back-offers",
		ShortUsage: "asc win-back-offers <subcommand> [flags]",
		ShortHelp:  "Manage win-back offers for subscriptions.",
		LongHelp: `Manage win-back offers for subscriptions.

Examples:
  asc win-back-offers list --subscription-id "SUB_ID"
  asc win-back-offers get --id "OFFER_ID"
  asc win-back-offers create --subscription-id "SUB_ID" --reference-name "spring-2026" --offer-id "OFFER-1" --duration ONE_MONTH --offer-mode PAY_AS_YOU_GO --period-count 1 --eligibility-paid-months 6 --eligibility-last-subscribed-min 3 --eligibility-last-subscribed-max 12 --start-date "2026-02-01" --priority HIGH --price "PRICE_ID"
  asc win-back-offers update --id "OFFER_ID" --priority NORMAL
  asc win-back-offers prices --id "OFFER_ID"`,
		FlagSet:   fs,
		UsageFunc: shared.VisibleUsageFunc,
		Subcommands: []*ffcli.Command{
			WinBackOffersListCommand(),
			WinBackOffersGetCommand(),
			WinBackOffersCreateCommand(),
			WinBackOffersUpdateCommand(),
			WinBackOffersDeleteCommand(),
			WinBackOffersPricesCommand(),
			WinBackOffersPricesRelationshipsCommand(),
			WinBackOffersRelationshipsCommand(),
		},
		Exec: func(ctx context.Context, args []string) error {
			return flag.ErrHelp
		},
	}
}

// WinBackOffersListCommand returns the win-back offers list subcommand.
func WinBackOffersListCommand() *ffcli.Command {
	fs := flag.NewFlagSet("list", flag.ExitOnError)

	subscriptionID := fs.String("subscription-id", "", "Subscription ID, product ID, or exact current name")
	appID := fs.String("app", "", "App Store Connect app ID (or ASC_APP_ID env; required when --subscription-id uses a product ID or name)")
	fields := fs.String("fields", "", "Fields to include: "+strings.Join(winBackOfferFieldsList(), ", "))
	priceFields := fs.String("price-fields", "", "Price fields to include: "+strings.Join(winBackOfferPriceFieldsList(), ", "))
	include := fs.String("include", "", "Include related resources: "+strings.Join(winBackOfferIncludeList(), ", "))
	pricesLimit := fs.Int("prices-limit", 0, "Maximum included prices per offer (1-50)")
	limit := fs.Int("limit", 0, "Maximum results per page (1-200)")
	next := fs.String("next", "", "Fetch next page using a links.next URL")
	paginate := fs.Bool("paginate", false, "Automatically fetch all pages (aggregate results)")
	output := shared.BindOutputFlags(fs)

	return &ffcli.Command{
		Name:       "list",
		ShortUsage: "asc win-back-offers list [flags]",
		ShortHelp:  "List win-back offers for a subscription.",
		LongHelp: `List win-back offers for a subscription.

Examples:
  asc win-back-offers list --subscription-id "SUB_ID"
  asc win-back-offers list --subscription-id "SUB_ID" --limit 50
  asc win-back-offers list --subscription-id "SUB_ID" --include prices --price-fields territory --prices-limit 10`,
		FlagSet:   fs,
		UsageFunc: shared.DefaultUsageFunc,
		Exec: func(ctx context.Context, args []string) error {
			if *limit != 0 && (*limit < 1 || *limit > winBackOffersMaxLimit) {
				return fmt.Errorf("win-back-offers list: --limit must be between 1 and %d", winBackOffersMaxLimit)
			}
			if err := shared.ValidateNextURL(*next); err != nil {
				return fmt.Errorf("win-back-offers list: %w", err)
			}
			if *pricesLimit != 0 && (*pricesLimit < 1 || *pricesLimit > winBackOffersPricesMaxLimit) {
				return fmt.Errorf("win-back-offers list: --prices-limit must be between 1 and %d", winBackOffersPricesMaxLimit)
			}

			fieldsValue, err := normalizeWinBackOfferFields(*fields, "--fields")
			if err != nil {
				return fmt.Errorf("win-back-offers list: %w", err)
			}
			priceFieldsValue, err := normalizeWinBackOfferPriceFields(*priceFields, "--price-fields")
			if err != nil {
				return fmt.Errorf("win-back-offers list: %w", err)
			}
			includeValue, err := normalizeWinBackOfferInclude(*include, "--include")
			if err != nil {
				return fmt.Errorf("win-back-offers list: %w", err)
			}
			if len(priceFieldsValue) > 0 && !shared.HasInclude(includeValue, "prices") {
				fmt.Fprintln(os.Stderr, "Error: --price-fields requires --include prices")
				return flag.ErrHelp
			}
			if *pricesLimit != 0 && !shared.HasInclude(includeValue, "prices") {
				fmt.Fprintln(os.Stderr, "Error: --prices-limit requires --include prices")
				return flag.ErrHelp
			}

			id := strings.TrimSpace(*subscriptionID)
			if id == "" && strings.TrimSpace(*next) == "" {
				fmt.Fprintln(os.Stderr, "Error: --subscription-id is required")
				return flag.ErrHelp
			}

			client, err := shared.GetASCClient()
			if err != nil {
				return fmt.Errorf("win-back-offers list: %w", err)
			}

			if strings.TrimSpace(*next) == "" {
				resolvedAppID := shared.ResolveAppID(strings.TrimSpace(*appID))
				if err := shared.RequireAppForStableSelector(resolvedAppID, id, "--subscription-id"); err != nil {
					return err
				}
				resolveCtx, resolveCancel := shared.ContextWithTimeout(ctx)
				id, err = shared.ResolveSubscriptionID(resolveCtx, client, resolvedAppID, id)
				resolveCancel()
				if err != nil {
					return err
				}
			}

			requestCtx, cancel := shared.ContextWithTimeout(ctx)
			defer cancel()

			opts := []asc.WinBackOffersOption{
				asc.WithWinBackOffersLimit(*limit),
				asc.WithWinBackOffersNextURL(*next),
				asc.WithWinBackOffersFields(fieldsValue),
				asc.WithWinBackOffersPriceFields(priceFieldsValue),
				asc.WithWinBackOffersInclude(includeValue),
				asc.WithWinBackOffersPricesLimit(*pricesLimit),
			}

			if *paginate {
				paginateOpts := append(opts, asc.WithWinBackOffersLimit(winBackOffersMaxLimit))
				firstPage, err := client.GetSubscriptionWinBackOffers(requestCtx, id, paginateOpts...)
				if err != nil {
					return fmt.Errorf("win-back-offers list: failed to fetch: %w", err)
				}

				resp, err := asc.PaginateAll(requestCtx, firstPage, func(ctx context.Context, nextURL string) (asc.PaginatedResponse, error) {
					return client.GetSubscriptionWinBackOffers(ctx, id, asc.WithWinBackOffersNextURL(nextURL))
				})
				if err != nil {
					return fmt.Errorf("win-back-offers list: %w", err)
				}

				return shared.PrintOutput(resp, *output.Output, *output.Pretty)
			}

			resp, err := client.GetSubscriptionWinBackOffers(requestCtx, id, opts...)
			if err != nil {
				return fmt.Errorf("win-back-offers list: failed to fetch: %w", err)
			}

			return shared.PrintOutput(resp, *output.Output, *output.Pretty)
		},
	}
}

// WinBackOffersGetCommand returns the win-back offers get subcommand.
func WinBackOffersGetCommand() *ffcli.Command {
	return shared.BuildIDGetCommand(shared.IDGetCommandConfig{
		FlagSetName: "get",
		Name:        "get",
		ShortUsage:  "asc win-back-offers get --id OFFER_ID",
		ShortHelp:   "Get a win-back offer by ID.",
		LongHelp: `Get a win-back offer by ID.

Examples:
  asc win-back-offers get --id "OFFER_ID"`,
		IDFlag:      "id",
		IDUsage:     "Win-back offer ID",
		ErrorPrefix: "win-back-offers get",
		Fetch: func(ctx context.Context, client *asc.Client, id string) (any, error) {
			return client.GetWinBackOffer(ctx, id)
		},
	})
}

// WinBackOffersCreateCommand returns the win-back offers create subcommand.
func WinBackOffersCreateCommand() *ffcli.Command {
	fs := flag.NewFlagSet("create", flag.ExitOnError)

	subscriptionID := fs.String("subscription-id", "", "Subscription ID, product ID, or exact current name")
	appID := fs.String("app", "", "App Store Connect app ID (or ASC_APP_ID env; required when --subscription-id uses a product ID or name)")
	referenceName := fs.String("reference-name", "", "Reference name")
	offerID := fs.String("offer-id", "", "Offer ID")
	duration := fs.String("duration", "", "Offer duration: "+strings.Join(winBackOfferDurationValues, ", "))
	offerMode := fs.String("offer-mode", "", "Offer mode: "+strings.Join(winBackOfferModeValues, ", "))
	var periodCount optionalInt
	fs.Var(&periodCount, "period-count", "Number of periods (required)")
	var eligibilityPaidMonths optionalInt
	fs.Var(&eligibilityPaidMonths, "eligibility-paid-months", "Paid subscription duration in months (required)")
	var eligibilityLastSubscribedMin optionalInt
	fs.Var(&eligibilityLastSubscribedMin, "eligibility-last-subscribed-min", "Minimum months since last subscribed")
	var eligibilityLastSubscribedMax optionalInt
	fs.Var(&eligibilityLastSubscribedMax, "eligibility-last-subscribed-max", "Maximum months since last subscribed")
	var eligibilityWaitMonths optionalInt
	fs.Var(&eligibilityWaitMonths, "eligibility-wait-months", "Wait between offers in months (optional)")
	startDate := fs.String("start-date", "", "Start date (YYYY-MM-DD)")
	endDate := fs.String("end-date", "", "End date (YYYY-MM-DD)")
	priority := fs.String("priority", "", "Offer priority: "+strings.Join(winBackOfferPriorityValues, ", "))
	promotionIntent := fs.String("promotion-intent", "", "Promotion intent: "+strings.Join(winBackOfferPromotionIntentValues, ", "))
	priceIDs := fs.String("price", "", "Win-back offer price ID(s), comma-separated")
	output := shared.BindOutputFlags(fs)

	return &ffcli.Command{
		Name:       "create",
		ShortUsage: "asc win-back-offers create [flags]",
		ShortHelp:  "Create a win-back offer.",
		LongHelp: `Create a win-back offer.

Examples:
  asc win-back-offers create --subscription-id "SUB_ID" --reference-name "spring-2026" --offer-id "OFFER-1" --duration ONE_MONTH --offer-mode PAY_AS_YOU_GO --period-count 1 --eligibility-paid-months 6 --eligibility-last-subscribed-min 3 --eligibility-last-subscribed-max 12 --start-date "2026-02-01" --priority HIGH --price "PRICE_ID"`,
		FlagSet:   fs,
		UsageFunc: shared.DefaultUsageFunc,
		Exec: func(ctx context.Context, args []string) error {
			subscription := strings.TrimSpace(*subscriptionID)
			if subscription == "" {
				fmt.Fprintln(os.Stderr, "Error: --subscription-id is required")
				return flag.ErrHelp
			}

			name := strings.TrimSpace(*referenceName)
			if name == "" {
				fmt.Fprintln(os.Stderr, "Error: --reference-name is required")
				return flag.ErrHelp
			}

			offer := strings.TrimSpace(*offerID)
			if offer == "" {
				fmt.Fprintln(os.Stderr, "Error: --offer-id is required")
				return flag.ErrHelp
			}

			if strings.TrimSpace(*duration) == "" {
				fmt.Fprintln(os.Stderr, "Error: --duration is required")
				return flag.ErrHelp
			}
			durationValue, err := normalizeWinBackOfferDuration(*duration)
			if err != nil {
				return fmt.Errorf("win-back-offers create: %w", err)
			}

			if strings.TrimSpace(*offerMode) == "" {
				fmt.Fprintln(os.Stderr, "Error: --offer-mode is required")
				return flag.ErrHelp
			}
			offerModeValue, err := normalizeWinBackOfferMode(*offerMode)
			if err != nil {
				return fmt.Errorf("win-back-offers create: %w", err)
			}

			if !periodCount.set {
				fmt.Fprintln(os.Stderr, "Error: --period-count is required")
				return flag.ErrHelp
			}
			if periodCount.value <= 0 {
				return fmt.Errorf("win-back-offers create: --period-count must be greater than 0")
			}

			if !eligibilityPaidMonths.set {
				fmt.Fprintln(os.Stderr, "Error: --eligibility-paid-months is required")
				return flag.ErrHelp
			}
			if eligibilityPaidMonths.value < 0 {
				return fmt.Errorf("win-back-offers create: --eligibility-paid-months must be 0 or greater")
			}

			if !eligibilityLastSubscribedMin.set && !eligibilityLastSubscribedMax.set {
				fmt.Fprintln(os.Stderr, "Error: --eligibility-last-subscribed-min or --eligibility-last-subscribed-max is required")
				return flag.ErrHelp
			}
			if eligibilityLastSubscribedMin.set && eligibilityLastSubscribedMin.value < 0 {
				return fmt.Errorf("win-back-offers create: eligibility last subscribed min must be 0 or greater")
			}
			if eligibilityLastSubscribedMax.set && eligibilityLastSubscribedMax.value < 0 {
				return fmt.Errorf("win-back-offers create: eligibility last subscribed max must be 0 or greater")
			}
			if eligibilityLastSubscribedMin.set && eligibilityLastSubscribedMax.set && eligibilityLastSubscribedMin.value > eligibilityLastSubscribedMax.value {
				return fmt.Errorf("win-back-offers create: eligibility last subscribed min must be less than or equal to max")
			}

			rangeValue := asc.IntegerRange{}
			if eligibilityLastSubscribedMin.set {
				rangeValue.Minimum = &eligibilityLastSubscribedMin.value
			}
			if eligibilityLastSubscribedMax.set {
				rangeValue.Maximum = &eligibilityLastSubscribedMax.value
			}

			if strings.TrimSpace(*startDate) == "" {
				fmt.Fprintln(os.Stderr, "Error: --start-date is required")
				return flag.ErrHelp
			}
			normalizedStartDate, err := shared.NormalizeDate(*startDate, "--start-date")
			if err != nil {
				return fmt.Errorf("win-back-offers create: %w", err)
			}

			if strings.TrimSpace(*priority) == "" {
				fmt.Fprintln(os.Stderr, "Error: --priority is required")
				return flag.ErrHelp
			}
			priorityValue, err := normalizeWinBackOfferPriority(*priority)
			if err != nil {
				return fmt.Errorf("win-back-offers create: %w", err)
			}

			prices := shared.SplitCSV(*priceIDs)
			if len(prices) == 0 {
				fmt.Fprintln(os.Stderr, "Error: --price is required")
				return flag.ErrHelp
			}

			if eligibilityWaitMonths.set && eligibilityWaitMonths.value < 0 {
				return fmt.Errorf("win-back-offers create: --eligibility-wait-months must be 0 or greater")
			}

			normalizedEndDate := ""
			if strings.TrimSpace(*endDate) != "" {
				normalizedEndDate, err = shared.NormalizeDate(*endDate, "--end-date")
				if err != nil {
					return fmt.Errorf("win-back-offers create: %w", err)
				}
			}

			var promotionIntentValue *asc.WinBackOfferPromotionIntent
			if strings.TrimSpace(*promotionIntent) != "" {
				intent, err := normalizeWinBackOfferPromotionIntent(*promotionIntent)
				if err != nil {
					return fmt.Errorf("win-back-offers create: %w", err)
				}
				promotionIntentValue = &intent
			}

			priceData := make([]asc.ResourceData, 0, len(prices))
			for _, priceID := range prices {
				priceData = append(priceData, asc.ResourceData{
					Type: asc.ResourceTypeWinBackOfferPrices,
					ID:   priceID,
				})
			}

			var waitBetween *int
			if eligibilityWaitMonths.set {
				waitBetween = &eligibilityWaitMonths.value
			}

			var endDateValue *string
			if normalizedEndDate != "" {
				endDateValue = &normalizedEndDate
			}

			client, err := shared.GetASCClient()
			if err != nil {
				return fmt.Errorf("win-back-offers create: %w", err)
			}

			resolvedAppID := shared.ResolveAppID(strings.TrimSpace(*appID))
			if err := shared.RequireAppForStableSelector(resolvedAppID, subscription, "--subscription-id"); err != nil {
				return err
			}
			resolveCtx, resolveCancel := shared.ContextWithTimeout(ctx)
			subscription, err = shared.ResolveSubscriptionID(resolveCtx, client, resolvedAppID, subscription)
			resolveCancel()
			if err != nil {
				return err
			}

			requestCtx, cancel := shared.ContextWithTimeout(ctx)
			defer cancel()

			req := asc.WinBackOfferCreateRequest{
				Data: asc.WinBackOfferCreateData{
					Type: asc.ResourceTypeWinBackOffers,
					Attributes: asc.WinBackOfferCreateAttributes{
						ReferenceName: name,
						OfferID:       offer,
						Duration:      durationValue,
						OfferMode:     offerModeValue,
						PeriodCount:   periodCount.value,
						CustomerEligibilityPaidSubscriptionDurationInMonths: eligibilityPaidMonths.value,
						CustomerEligibilityTimeSinceLastSubscribedInMonths:  rangeValue,
						CustomerEligibilityWaitBetweenOffersInMonths:        waitBetween,
						StartDate:       normalizedStartDate,
						EndDate:         endDateValue,
						Priority:        priorityValue,
						PromotionIntent: promotionIntentValue,
					},
					Relationships: asc.WinBackOfferCreateRelationships{
						Subscription: asc.Relationship{
							Data: asc.ResourceData{
								Type: asc.ResourceTypeSubscriptions,
								ID:   subscription,
							},
						},
						Prices: asc.RelationshipList{Data: priceData},
					},
				},
			}

			resp, err := client.CreateWinBackOffer(requestCtx, req)
			if err != nil {
				return fmt.Errorf("win-back-offers create: failed to create: %w", err)
			}

			return shared.PrintOutput(resp, *output.Output, *output.Pretty)
		},
	}
}

// WinBackOffersUpdateCommand returns the win-back offers update subcommand.
func WinBackOffersUpdateCommand() *ffcli.Command {
	fs := flag.NewFlagSet("update", flag.ExitOnError)

	id := fs.String("id", "", "Win-back offer ID")
	var eligibilityPaidMonths optionalInt
	fs.Var(&eligibilityPaidMonths, "eligibility-paid-months", "Paid subscription duration in months")
	var eligibilityLastSubscribedMin optionalInt
	fs.Var(&eligibilityLastSubscribedMin, "eligibility-last-subscribed-min", "Minimum months since last subscribed")
	var eligibilityLastSubscribedMax optionalInt
	fs.Var(&eligibilityLastSubscribedMax, "eligibility-last-subscribed-max", "Maximum months since last subscribed")
	var eligibilityWaitMonths optionalInt
	fs.Var(&eligibilityWaitMonths, "eligibility-wait-months", "Wait between offers in months")
	startDate := fs.String("start-date", "", "Start date (YYYY-MM-DD)")
	endDate := fs.String("end-date", "", "End date (YYYY-MM-DD)")
	priority := fs.String("priority", "", "Offer priority: "+strings.Join(winBackOfferPriorityValues, ", "))
	promotionIntent := fs.String("promotion-intent", "", "Promotion intent: "+strings.Join(winBackOfferPromotionIntentValues, ", "))
	output := shared.BindOutputFlags(fs)

	return &ffcli.Command{
		Name:       "update",
		ShortUsage: "asc win-back-offers update [flags]",
		ShortHelp:  "Update a win-back offer.",
		LongHelp: `Update a win-back offer.

Examples:
  asc win-back-offers update --id "OFFER_ID" --priority NORMAL
  asc win-back-offers update --id "OFFER_ID" --end-date "2026-04-01"`,
		FlagSet:   fs,
		UsageFunc: shared.DefaultUsageFunc,
		Exec: func(ctx context.Context, args []string) error {
			trimmedID := strings.TrimSpace(*id)
			if trimmedID == "" {
				fmt.Fprintln(os.Stderr, "Error: --id is required")
				return flag.ErrHelp
			}

			hasUpdates := false
			attrs := asc.WinBackOfferUpdateAttributes{}

			if eligibilityPaidMonths.set {
				if eligibilityPaidMonths.value < 0 {
					return fmt.Errorf("win-back-offers update: --eligibility-paid-months must be 0 or greater")
				}
				attrs.CustomerEligibilityPaidSubscriptionDurationInMonths = &eligibilityPaidMonths.value
				hasUpdates = true
			}

			if eligibilityLastSubscribedMin.set || eligibilityLastSubscribedMax.set {
				if eligibilityLastSubscribedMin.set && eligibilityLastSubscribedMin.value < 0 {
					return fmt.Errorf("win-back-offers update: eligibility last subscribed min must be 0 or greater")
				}
				if eligibilityLastSubscribedMax.set && eligibilityLastSubscribedMax.value < 0 {
					return fmt.Errorf("win-back-offers update: eligibility last subscribed max must be 0 or greater")
				}
				if eligibilityLastSubscribedMin.set && eligibilityLastSubscribedMax.set && eligibilityLastSubscribedMin.value > eligibilityLastSubscribedMax.value {
					return fmt.Errorf("win-back-offers update: eligibility last subscribed min must be less than or equal to max")
				}
				rangeValue := asc.IntegerRange{}
				if eligibilityLastSubscribedMin.set {
					rangeValue.Minimum = &eligibilityLastSubscribedMin.value
				}
				if eligibilityLastSubscribedMax.set {
					rangeValue.Maximum = &eligibilityLastSubscribedMax.value
				}
				attrs.CustomerEligibilityTimeSinceLastSubscribedInMonths = &rangeValue
				hasUpdates = true
			}

			if eligibilityWaitMonths.set {
				if eligibilityWaitMonths.value < 0 {
					return fmt.Errorf("win-back-offers update: --eligibility-wait-months must be 0 or greater")
				}
				attrs.CustomerEligibilityWaitBetweenOffersInMonths = &eligibilityWaitMonths.value
				hasUpdates = true
			}

			if strings.TrimSpace(*startDate) != "" {
				normalized, err := shared.NormalizeDate(*startDate, "--start-date")
				if err != nil {
					return fmt.Errorf("win-back-offers update: %w", err)
				}
				attrs.StartDate = &normalized
				hasUpdates = true
			}

			if strings.TrimSpace(*endDate) != "" {
				normalized, err := shared.NormalizeDate(*endDate, "--end-date")
				if err != nil {
					return fmt.Errorf("win-back-offers update: %w", err)
				}
				attrs.EndDate = &normalized
				hasUpdates = true
			}

			if strings.TrimSpace(*priority) != "" {
				value, err := normalizeWinBackOfferPriority(*priority)
				if err != nil {
					return fmt.Errorf("win-back-offers update: %w", err)
				}
				attrs.Priority = &value
				hasUpdates = true
			}

			if strings.TrimSpace(*promotionIntent) != "" {
				value, err := normalizeWinBackOfferPromotionIntent(*promotionIntent)
				if err != nil {
					return fmt.Errorf("win-back-offers update: %w", err)
				}
				attrs.PromotionIntent = &value
				hasUpdates = true
			}

			if !hasUpdates {
				fmt.Fprintln(os.Stderr, "Error: at least one update flag is required")
				return flag.ErrHelp
			}

			client, err := shared.GetASCClient()
			if err != nil {
				return fmt.Errorf("win-back-offers update: %w", err)
			}

			requestCtx, cancel := shared.ContextWithTimeout(ctx)
			defer cancel()

			resp, err := client.UpdateWinBackOffer(requestCtx, trimmedID, attrs)
			if err != nil {
				return fmt.Errorf("win-back-offers update: failed to update: %w", err)
			}

			return shared.PrintOutput(resp, *output.Output, *output.Pretty)
		},
	}
}

// WinBackOffersDeleteCommand returns the win-back offers delete subcommand.
func WinBackOffersDeleteCommand() *ffcli.Command {
	fs := flag.NewFlagSet("delete", flag.ExitOnError)

	id := fs.String("id", "", "Win-back offer ID")
	confirm := fs.Bool("confirm", false, "Confirm deletion")
	output := shared.BindOutputFlags(fs)

	return &ffcli.Command{
		Name:       "delete",
		ShortUsage: "asc win-back-offers delete --id OFFER_ID --confirm",
		ShortHelp:  "Delete a win-back offer.",
		LongHelp: `Delete a win-back offer.

Examples:
  asc win-back-offers delete --id "OFFER_ID" --confirm`,
		FlagSet:   fs,
		UsageFunc: shared.DefaultUsageFunc,
		Exec: func(ctx context.Context, args []string) error {
			trimmedID := strings.TrimSpace(*id)
			if trimmedID == "" {
				fmt.Fprintln(os.Stderr, "Error: --id is required")
				return flag.ErrHelp
			}
			if !*confirm {
				fmt.Fprintln(os.Stderr, "Error: --confirm is required")
				return flag.ErrHelp
			}

			client, err := shared.GetASCClient()
			if err != nil {
				return fmt.Errorf("win-back-offers delete: %w", err)
			}

			requestCtx, cancel := shared.ContextWithTimeout(ctx)
			defer cancel()

			if err := client.DeleteWinBackOffer(requestCtx, trimmedID); err != nil {
				return fmt.Errorf("win-back-offers delete: failed to delete: %w", err)
			}

			result := &asc.WinBackOfferDeleteResult{
				ID:      trimmedID,
				Deleted: true,
			}

			return shared.PrintOutput(result, *output.Output, *output.Pretty)
		},
	}
}

// WinBackOffersPricesCommand returns the win-back offers prices subcommand.
func WinBackOffersPricesCommand() *ffcli.Command {
	fs := flag.NewFlagSet("prices", flag.ExitOnError)

	id := fs.String("id", "", "Win-back offer ID")
	territories := fs.String("territory", "", "Territory inputs, comma-separated (accepts alpha-2, alpha-3, or exact English country names)")
	fields := fs.String("fields", "", "Fields to include: "+strings.Join(winBackOfferPriceFieldsList(), ", "))
	territoryFields := fs.String("territory-fields", "", "Territory fields to include: "+strings.Join(winBackOfferTerritoryFieldsList(), ", "))
	pricePointFields := fs.String("price-point-fields", "", "Price point fields to include: "+strings.Join(winBackOfferSubscriptionPricePointFieldsList(), ", "))
	include := fs.String("include", "", "Include related resources: "+strings.Join(winBackOfferPriceIncludeList(), ", "))
	limit := fs.Int("limit", 0, "Maximum results per page (1-200)")
	next := fs.String("next", "", "Fetch next page using a links.next URL")
	paginate := fs.Bool("paginate", false, "Automatically fetch all pages (aggregate results)")
	output := shared.BindOutputFlags(fs)

	return &ffcli.Command{
		Name:       "prices",
		ShortUsage: "asc win-back-offers prices --id OFFER_ID [flags]",
		ShortHelp:  "List prices for a win-back offer.",
		LongHelp: `List prices for a win-back offer.

Examples:
  asc win-back-offers prices --id "OFFER_ID"
  asc win-back-offers prices --id "OFFER_ID" --territory "US,France" --include territory --territory-fields currency`,
		FlagSet:   fs,
		UsageFunc: shared.DefaultUsageFunc,
		Exec: func(ctx context.Context, args []string) error {
			if *limit != 0 && (*limit < 1 || *limit > winBackOffersMaxLimit) {
				return fmt.Errorf("win-back-offers prices: --limit must be between 1 and %d", winBackOffersMaxLimit)
			}
			if err := shared.ValidateNextURL(*next); err != nil {
				return fmt.Errorf("win-back-offers prices: %w", err)
			}

			trimmedID := strings.TrimSpace(*id)
			if trimmedID == "" && strings.TrimSpace(*next) == "" {
				fmt.Fprintln(os.Stderr, "Error: --id is required")
				return flag.ErrHelp
			}

			fieldsValue, err := normalizeWinBackOfferPriceFields(*fields, "--fields")
			if err != nil {
				return fmt.Errorf("win-back-offers prices: %w", err)
			}
			territoryFieldsValue, err := normalizeWinBackOfferTerritoryFields(*territoryFields, "--territory-fields")
			if err != nil {
				return fmt.Errorf("win-back-offers prices: %w", err)
			}
			pricePointFieldsValue, err := normalizeWinBackOfferSubscriptionPricePointFields(*pricePointFields, "--price-point-fields")
			if err != nil {
				return fmt.Errorf("win-back-offers prices: %w", err)
			}
			includeValue, err := normalizeWinBackOfferPriceInclude(*include, "--include")
			if err != nil {
				return fmt.Errorf("win-back-offers prices: %w", err)
			}
			territoryFilter, err := shared.NormalizeASCTerritoryCSV(*territories)
			if err != nil {
				return shared.UsageError(err.Error())
			}
			if len(territoryFieldsValue) > 0 && !shared.HasInclude(includeValue, "territory") {
				fmt.Fprintln(os.Stderr, "Error: --territory-fields requires --include territory")
				return flag.ErrHelp
			}
			if len(pricePointFieldsValue) > 0 && !shared.HasInclude(includeValue, "subscriptionPricePoint") {
				fmt.Fprintln(os.Stderr, "Error: --price-point-fields requires --include subscriptionPricePoint")
				return flag.ErrHelp
			}

			client, err := shared.GetASCClient()
			if err != nil {
				return fmt.Errorf("win-back-offers prices: %w", err)
			}

			requestCtx, cancel := shared.ContextWithTimeout(ctx)
			defer cancel()

			opts := []asc.WinBackOfferPricesOption{
				asc.WithWinBackOfferPricesLimit(*limit),
				asc.WithWinBackOfferPricesNextURL(*next),
				asc.WithWinBackOfferPricesTerritoryFilter(territoryFilter),
				asc.WithWinBackOfferPricesFields(fieldsValue),
				asc.WithWinBackOfferPricesTerritoryFields(territoryFieldsValue),
				asc.WithWinBackOfferPricesSubscriptionPricePointFields(pricePointFieldsValue),
				asc.WithWinBackOfferPricesInclude(includeValue),
			}

			if *paginate {
				paginateOpts := append(opts, asc.WithWinBackOfferPricesLimit(winBackOffersMaxLimit))
				firstPage, err := client.GetWinBackOfferPrices(requestCtx, trimmedID, paginateOpts...)
				if err != nil {
					return fmt.Errorf("win-back-offers prices: failed to fetch: %w", err)
				}

				resp, err := asc.PaginateAll(requestCtx, firstPage, func(ctx context.Context, nextURL string) (asc.PaginatedResponse, error) {
					return client.GetWinBackOfferPrices(ctx, trimmedID, asc.WithWinBackOfferPricesNextURL(nextURL))
				})
				if err != nil {
					return fmt.Errorf("win-back-offers prices: %w", err)
				}

				return shared.PrintOutput(resp, *output.Output, *output.Pretty)
			}

			resp, err := client.GetWinBackOfferPrices(requestCtx, trimmedID, opts...)
			if err != nil {
				return fmt.Errorf("win-back-offers prices: failed to fetch: %w", err)
			}

			return shared.PrintOutput(resp, *output.Output, *output.Pretty)
		},
	}
}

// WinBackOffersPricesRelationshipsCommand returns the price links subcommand.
func WinBackOffersPricesRelationshipsCommand() *ffcli.Command {
	return shared.BuildPaginatedListCommand(shared.PaginatedListCommandConfig{
		FlagSetName: "prices-links",
		Name:        "prices-links",
		ShortUsage:  "asc win-back-offers prices-links --id OFFER_ID [flags]",
		ShortHelp:   "List price relationships for a win-back offer.",
		LongHelp: `List price relationships for a win-back offer.

Examples:
  asc win-back-offers prices-links --id "OFFER_ID"
  asc win-back-offers prices-links --id "OFFER_ID" --paginate`,
		ParentFlag:  "id",
		ParentUsage: "Win-back offer ID",
		LimitMax:    winBackOffersMaxLimit,
		ErrorPrefix: "win-back-offers prices-links",
		FetchPage: func(ctx context.Context, client *asc.Client, offerID string, limit int, next string) (asc.PaginatedResponse, error) {
			opts := []asc.LinkagesOption{
				asc.WithLinkagesLimit(limit),
				asc.WithLinkagesNextURL(next),
			}
			return client.GetWinBackOfferPricesRelationships(ctx, offerID, opts...)
		},
	})
}

// WinBackOffersRelationshipsCommand returns the win-back offer links subcommand.
func WinBackOffersRelationshipsCommand() *ffcli.Command {
	fs := flag.NewFlagSet("links", flag.ExitOnError)

	subscriptionID := fs.String("subscription-id", "", "Subscription ID, product ID, or exact current name")
	appID := fs.String("app", "", "App Store Connect app ID (or ASC_APP_ID env; required when --subscription-id uses a product ID or name)")
	limit := fs.Int("limit", 0, fmt.Sprintf("Maximum results per page (1-%d)", winBackOffersMaxLimit))
	next := fs.String("next", "", "Fetch next page using a links.next URL")
	paginate := fs.Bool("paginate", false, "Automatically fetch all pages (aggregate results)")
	output := shared.BindOutputFlags(fs)

	return &ffcli.Command{
		Name:       "links",
		ShortUsage: "asc win-back-offers links --subscription-id SUB_ID [flags]",
		ShortHelp:  "List win-back offer relationships for a subscription.",
		LongHelp: `List win-back offer relationships for a subscription.

Examples:
  asc win-back-offers links --subscription-id "SUB_ID"
  asc win-back-offers links --subscription-id "SUB_ID" --paginate`,
		FlagSet:   fs,
		UsageFunc: shared.DefaultUsageFunc,
		Exec: func(ctx context.Context, args []string) error {
			if *limit != 0 && (*limit < 1 || *limit > winBackOffersMaxLimit) {
				return fmt.Errorf("win-back-offers links: --limit must be between 1 and %d", winBackOffersMaxLimit)
			}
			if err := shared.ValidateNextURL(*next); err != nil {
				return fmt.Errorf("win-back-offers links: %w", err)
			}

			id := strings.TrimSpace(*subscriptionID)
			if id == "" && strings.TrimSpace(*next) == "" {
				return shared.UsageError("--subscription-id is required")
			}

			client, err := shared.GetASCClient()
			if err != nil {
				return fmt.Errorf("win-back-offers links: %w", err)
			}

			if strings.TrimSpace(*next) == "" {
				resolvedAppID := shared.ResolveAppID(strings.TrimSpace(*appID))
				if err := shared.RequireAppForStableSelector(resolvedAppID, id, "--subscription-id"); err != nil {
					return err
				}
				resolveCtx, resolveCancel := shared.ContextWithTimeout(ctx)
				id, err = shared.ResolveSubscriptionID(resolveCtx, client, resolvedAppID, id)
				resolveCancel()
				if err != nil {
					return err
				}
			}

			requestCtx, cancel := shared.ContextWithTimeout(ctx)
			defer cancel()

			fetchPage := func(ctx context.Context, perPage int, nextURL string) (asc.PaginatedResponse, error) {
				opts := []asc.LinkagesOption{
					asc.WithLinkagesLimit(perPage),
					asc.WithLinkagesNextURL(nextURL),
				}
				return client.GetSubscriptionWinBackOffersRelationships(ctx, id, opts...)
			}

			if *paginate {
				resp, err := shared.PaginateWithSpinner(
					requestCtx,
					func(ctx context.Context) (asc.PaginatedResponse, error) {
						return fetchPage(ctx, winBackOffersMaxLimit, *next)
					},
					func(ctx context.Context, nextURL string) (asc.PaginatedResponse, error) {
						return fetchPage(ctx, 0, nextURL)
					},
				)
				if err != nil {
					return fmt.Errorf("win-back-offers links: %w", err)
				}
				return shared.PrintOutput(resp, *output.Output, *output.Pretty)
			}

			resp, err := fetchPage(requestCtx, *limit, *next)
			if err != nil {
				return fmt.Errorf("win-back-offers links: %w", err)
			}
			return shared.PrintOutput(resp, *output.Output, *output.Pretty)
		},
	}
}

type optionalInt struct {
	set   bool
	value int
}

func (i *optionalInt) Set(value string) error {
	parsed, err := strconv.Atoi(strings.TrimSpace(value))
	if err != nil {
		return fmt.Errorf("must be an integer")
	}
	i.value = parsed
	i.set = true
	return nil
}

func (i *optionalInt) String() string {
	if !i.set {
		return ""
	}
	return strconv.Itoa(i.value)
}

func normalizeWinBackOfferDuration(value string) (asc.SubscriptionOfferDuration, error) {
	normalized := shared.NormalizeEnumToken(value)
	if normalized == "" {
		return "", nil
	}
	if duration, ok := winBackOfferDurationMap[normalized]; ok {
		return duration, nil
	}
	return "", fmt.Errorf("--duration must be one of: %s", strings.Join(winBackOfferDurationValues, ", "))
}

func normalizeWinBackOfferMode(value string) (asc.SubscriptionOfferMode, error) {
	normalized := shared.NormalizeEnumToken(value)
	if normalized == "" {
		return "", nil
	}
	if mode, ok := winBackOfferModeMap[normalized]; ok {
		return mode, nil
	}
	return "", fmt.Errorf("--offer-mode must be one of: %s", strings.Join(winBackOfferModeValues, ", "))
}

func normalizeWinBackOfferPriority(value string) (asc.WinBackOfferPriority, error) {
	normalized := shared.NormalizeEnumToken(value)
	if normalized == "" {
		return "", nil
	}
	if priority, ok := winBackOfferPriorityMap[normalized]; ok {
		return priority, nil
	}
	return "", fmt.Errorf("--priority must be one of: %s", strings.Join(winBackOfferPriorityValues, ", "))
}

func normalizeWinBackOfferPromotionIntent(value string) (asc.WinBackOfferPromotionIntent, error) {
	normalized := shared.NormalizeEnumToken(value)
	if normalized == "" {
		return "", nil
	}
	if intent, ok := winBackOfferPromotionIntentMap[normalized]; ok {
		return intent, nil
	}
	return "", fmt.Errorf("--promotion-intent must be one of: %s", strings.Join(winBackOfferPromotionIntentValues, ", "))
}

func normalizeWinBackOfferFields(value, flagName string) ([]string, error) {
	return shared.NormalizeSelection(value, winBackOfferFieldsList(), flagName)
}

func normalizeWinBackOfferPriceFields(value, flagName string) ([]string, error) {
	return shared.NormalizeSelection(value, winBackOfferPriceFieldsList(), flagName)
}

func normalizeWinBackOfferInclude(value, flagName string) ([]string, error) {
	return shared.NormalizeSelection(value, winBackOfferIncludeList(), flagName)
}

func normalizeWinBackOfferTerritoryFields(value, flagName string) ([]string, error) {
	return shared.NormalizeSelection(value, winBackOfferTerritoryFieldsList(), flagName)
}

func normalizeWinBackOfferSubscriptionPricePointFields(value, flagName string) ([]string, error) {
	return shared.NormalizeSelection(value, winBackOfferSubscriptionPricePointFieldsList(), flagName)
}

func normalizeWinBackOfferPriceInclude(value, flagName string) ([]string, error) {
	return shared.NormalizeSelection(value, winBackOfferPriceIncludeList(), flagName)
}

func winBackOfferFieldsList() []string {
	return []string{
		"referenceName",
		"offerId",
		"duration",
		"offerMode",
		"periodCount",
		"customerEligibilityPaidSubscriptionDurationInMonths",
		"customerEligibilityTimeSinceLastSubscribedInMonths",
		"customerEligibilityWaitBetweenOffersInMonths",
		"startDate",
		"endDate",
		"priority",
		"promotionIntent",
		"prices",
	}
}

func winBackOfferPriceFieldsList() []string {
	return []string{"territory", "subscriptionPricePoint"}
}

func winBackOfferIncludeList() []string {
	return []string{"prices"}
}

func winBackOfferTerritoryFieldsList() []string {
	return []string{"currency"}
}

func winBackOfferSubscriptionPricePointFieldsList() []string {
	return []string{"customerPrice", "proceeds", "proceedsYear2", "territory", "equalizations"}
}

func winBackOfferPriceIncludeList() []string {
	return []string{"territory", "subscriptionPricePoint"}
}
