// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {settings} from '../models';

export function ApproveAction(arg1:string):Promise<main.StudioApproval>;

export function Bootstrap():Promise<main.BootstrapData>;

export function CheckAuthStatus():Promise<main.AuthStatus>;

export function CreateThread(arg1:string):Promise<main.StudioThread>;

export function GetAppDetail(arg1:string):Promise<main.AppDetail>;

export function GetFeedback(arg1:string):Promise<main.FeedbackResponse>;

export function GetFinanceRegions():Promise<main.FinanceResponse>;

export function GetOfferCodes(arg1:string):Promise<main.OfferCodesResponse>;

export function GetPricingOverview(arg1:string):Promise<main.PricingOverview>;

export function GetScreenshots(arg1:string):Promise<main.ScreenshotsResponse>;

export function GetSettings():Promise<settings.StudioSettings>;

export function GetSubscriptions(arg1:string):Promise<main.SubscriptionsResponse>;

export function GetTestFlight(arg1:string):Promise<main.TestFlightResponse>;

export function GetTestFlightTesters(arg1:string):Promise<main.TestFlightResponse>;

export function GetVersionMetadata(arg1:string):Promise<main.VersionMetadataResponse>;

export function ListApprovals():Promise<Array<main.StudioApproval>>;

export function ListApps():Promise<main.ListAppsResponse>;

export function ListThreads():Promise<Array<main.StudioThread>>;

export function QueueMutation(arg1:main.ApprovalRequest):Promise<main.StudioApproval>;

export function RejectAction(arg1:string):Promise<main.StudioApproval>;

export function ResolveASC():Promise<main.ResolutionResponse>;

export function RunASCCommand(arg1:string):Promise<main.ASCCommandResponse>;

export function SaveSettings(arg1:settings.StudioSettings):Promise<settings.StudioSettings>;

export function SendPrompt(arg1:main.PromptRequest):Promise<main.PromptResponse>;
